// src/lib/ui/KForm.vue
<template>
  <div class="form">
    <slot></slot>
  </div>  
</template>
<script>
import {verify} from '@/lib/utils/verify.js'
let verify_api = verify;
export default {
  name: 'KForm',

  data(){
    return {
      elements:[]
    }
  },

  computed:{},

  methods:{
    params(){
      let param = {};
      this.elements.map(ele=>{
        if( ele.name ){
          param[ ele.name ] = ele.value
        }
      })
      return param;
    },
    verify(){
      let childs = this.elements;
      let result = null;
      for(let i=0;i< childs.length ;i++){
        result =this.verifyElement( childs[i] );
        if( !result || (typeof result=='object' && !result.result)){
          result = false;
          break;
        }
      }
      return result;
    },
    verifyElement( component ){
      let {value,rule,error} = component;
      let res = verify_api.verify( component, { value, rule, error })
      if( !res || (typeof res=='object' && !res.result) ){
        component.errorInfo( res ? res.error: verify_api.option.error )
        return res;
      }else{
        component.errorClear();
      }
      return true;
    }
  },
  mounted(){
    let childs = (this.$children || []).filter(ele=>{
      return ele && ele.defaultClassName == 'form-control'
    })
    this.elements = childs;
    this.elements.map(ele=>{
      //console.log("控件:", ele.name, ele)
      ele.$on('blur',evt=>{
        this.verifyElement( ele )
      })
      ele.$on('change',evt=>{
        this.verifyElement( ele )
      })
    })
  },
}
</script>

// src/lib/ui/react/KForm.js
import React, { Component } from 'react';
import ReactDOM from 'react-dom'

import {KFormElement} from './index.js'
import {domquery as query} from '@/lib/utils/domquery.js'
import verify from '@/lib/utils/verify.js'
import {env} from '@/lib/env.js';
console.log('verify',verify, 'env====',env)
let verify_api = verify;
export default class KForm extends Component {
  constructor(props) {
    super( props );
    // 组件所在的DOM父容器
    this.refs = [];
    // 组件实例
    this.components = [];
  }

  verify(){
    let result = null;
    for( let i=0;i<this.components.length;i++){
      if( this.components[i]){
        let { rule, error } = this.components[i].props;
        result =this.verifyElement( this.components[i] );
        if( !result || (typeof result=='object' && !result.result)){
          result = false;
          break;
        }
      }
    }
  }
  /**
   * @param {KFormElement} component 组件实例
   */
  verifyElement( component ){
    console.log('verify:', component)
    let {rule,error,disabled} = component.props;
    let value = component.value;
    if( disabled ){
      return true;
    }
    let res = verify_api.verify( component, { value, rule, error })
    if( !res || (typeof res=='object' && !res.result) ){
      component.errorInfo( res ? res.error: verify_api.option.error )
      return res;
    }else{
      component.errorClear();
    }
    return true;
  }

  params(){
    let param = {}
    this.components.map( ele =>{
      if( ele.props.name ){
        if( !ele.props.disabled ){
          //不可用的组件忽略
          param[ ele.props.name ] = ele.value;
        }        
      }
    })
    return param;
  }

  onFormElementMounted( element ){
    this.components.push( element )
    console.log("***formelement found", element)
  }

  onFormElementBlur( element ){
    this.verifyElement( element );
  }
  onFormElementChange( element ){
    this.verifyElement( element )
  }

  componentDidMount() {
    console.log("form mounted this.refs",this.refs, this.components)
  }

  
  render(){
    let deepClone = ( children )=>{
      if( Array.isArray( children ) ){
        return React.Children.map( children, child =>{
          return deepClone( child );
        })
      }else{
        //找到组件，就添加 FormElementMounted事件
        if( typeof children.type == 'function'){          
          let newProps = { 
            ...children.props,
            onFormElementMounted: this.onFormElementMounted.bind( this ),
            onFormElementBlur:this.onFormElementBlur.bind( this ),
            onFormElementChange:this.onFormElementChange.bind( this )
          }
          let clone = React.cloneElement( children, {
            ...newProps
          })
          return clone
        }else{
          let childs = children.props.children;
          
          if( Array.isArray( childs ) || typeof childs=='object'){
            childs = deepClone( childs );
          }
          return React.cloneElement( children, {
            ...children.props,
          }, childs)
        }
      }
    };
    let children = this.props.children;
    let cls = "form";
    if( env.mobile ){
      cls += ' form-mobile';
    }
    return (
      <div className={cls}>
      { deepClone( children ) }
      </div>
    )
  }
}
