// src/lib/ui/react/KFormElement.js
import React, { Component } from 'react';
import query from '@/lib/utils/domquery.js'
export default class KFormElement extends Component {  
  constructor(props) {
    super(props);
    this.id = "kui" + (~~ (Math.random() * 1000));
    this.state = {
      checked:false,
      value: this.props.value, 
      rule: this.props['data-rule'],
      error: this.props['data-error'],
      //是否表单验证正确
      valid: true,
    };
    this.ref = React.createRef();
  }

  static defaultProps={
    defaultclass:'form-control',
    defaultInvalidClass:'form-control-invalid',
    disabled:false,
  }

  set opacity( alpha ){
    if( this.ref.current ){
      query( this.ref.current ).css("opacity", alpha);
    }
  }

  get value(){
    return this.state.value ||'';
  }

  /** 返回样式名 */
  getClassName(){
    let validCls = (typeof this.state.valid=='boolean' && !this.state.valid) ? this.props.defaultInvalidClass :'';
    let disabledCls = this.props.disabled ? ' form-control-disabled':''
    return [ this.props.defaultclass, validCls, disabledCls,  this.props.className || '',this.id ].join(" ")
  }

  errorInfo( msg ){
    let dom = this.ref.current;
    if( !dom )return;
    let wrapper = dom.parentNode;
    let err = wrapper.querySelector('.err-tip');
    if( !err ){
      err = document.createElement('span');
      err.className = 'err-tip';
      wrapper.appendChild( err )
    }
    err.innerHTML = msg;
    this.setState({
      valid:false
    })
  }

  errorClear(){
    let dom = this.ref.current;
    if( !dom )return;
    let wrapper = dom.parentNode;
    let err = wrapper.querySelector('.err-tip');
    if( err ){
      err.innerHTML = '';
    }
    this.setState({
      valid:true
    })
  }

  //componentWillMount(){}
  componentDidMount(){
    if( this.props.onFormElementMounted ){
      this.props.onFormElementMounted( this )
    }
  }

  onComponentBlur(){
   if( this.props.onFormElementBlur ){
      this.props.onFormElementBlur( this )
    }
  } 
  onComponentChange(){
    if( this.props.onFormElementChange ){
      this.props.onFormElementChange( this )
    }
  }
  //componentWillUpdate(nextProps, nextState){}
  componentDidUpdate(prevProps, prevState){}
  /*
  componentWillReceiveProps( nextProps ){
    console.log("nextProps",nextProps)
    if(nextProps.value !== this.props.value){
      this.setState({value:nextProps.value})
    }
  }
  */

  /*
  shouldComponentUpdate(){
    console.log('shouldComponentUpdate')
  }
  */
}

// src/lib/ui/vue/KFormElement.vue
<template>
  <div>
    <slot></slot>
  </div>
</template>
<script>
export default {
  name: 'KFormElement',
  data(){
    return {
      guid: 'kui' + (~~(Math.random()* 1000)),
      //组件的真实值
      value:'',
      //有些组件有二态，未选中value为空，cacheValue用于缓存实际值
      cacheValue:'',
      //是否表单校验出错
      verifyError:false,
      defaultClassName:'form-control'
    }
  },
  computed:{

  },
  props:{
    className:{
      type:String
    }
  },
  methods:{
    /** 组件的样式类名 **/
    getClassName(){
      return this.defaultClassName + " " + (  this.verifyError?" form-control-error ":"") + (this.className || '')
    },
    errorInfo( msg ){
      this.verifyError = true;
      let wrapper = this.$el.parentNode;
      let err = wrapper.querySelector('.err-tip');
      if( !err ){
        err = document.createElement('span');
        err.className = 'err-tip';
        wrapper.appendChild( err )
      }
      err.innerHTML = msg;
    },
    errorClear(){
      this.verifyError = false;
      let wrapper = this.$el;
      let err = wrapper.querySelector('.err-tip');
      if( err ){
        err.innerHTML = '';
      }
    }
  },
  mounted(){
    this.rule = this.$attrs["rule"]||''
    this.error = this.$attrs["error"]||''
    this.name = this.$attrs['name']||''
    this.value = this.$attrs['value']||'';
    this.defaultValue = this.$attrs['value'];
    this.cacheValue = this.value;
  },
}
</script>
